name = "baidaohui"
compatibility_date = "2024-01-01"

# Cloudflare Pages 配置
pages_build_output_dir = ".svelte-kit/cloudflare"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "modules"
dir = "build"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production]
name = "baidaohui-production"

[env.preview]
name = "baidaohui-preview" 