name = "baidaohui"
compatibility_date = "2024-01-01"

# Cloudflare Pages 配置
pages_build_output_dir = ".svelte-kit/cloudflare"

[env.production]
name = "baidaohui-production"

[env.preview]
name = "baidaohui-preview" 