version: '3.8'

networks:
  baidaohui-network:
    driver: bridge

volumes:
  redis_data:
  mongodb_data:

services:
  # 开发环境MongoDB (可选 - 也可使用MongoDB Atlas)
  mongodb:
    image: mongo:5.0
    container_name: baidaohui-mongodb-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=baidaohui
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - baidaohui-network

  # Redis缓存服务
  redis:
    image: redis:alpine
    container_name: baidaohui-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - baidaohui-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 认证服务
  auth-service:
    build: ../services/auth-service
    container_name: auth-service-dev
    environment:
      # 外部API配置 - 从.env文件读取
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:password@mongodb:27017/baidaohui?authSource=admin}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      # 内部配置 - 开发环境
      - NODE_ENV=development
      - PORT=5001
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - SSO_SERVICE_URL=http://sso-service:5002
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - mongodb
    networks:
      - baidaohui-network

  # SSO统一认证服务
  sso-service:
    build: ../services/sso-service
    container_name: sso-service-dev
    environment:
      # 外部API配置
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:password@mongodb:27017/baidaohui?authSource=admin}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      # 内部配置
      - NODE_ENV=development
      - PORT=5002
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - DOMAIN=localhost
      - CORS_ORIGINS=http://localhost:5173,http://localhost:4173
    ports:
      - "5002:5002"
    depends_on:
      - redis
      - mongodb
    networks:
      - baidaohui-network

  # 聊天服务
  chat-service:
    build: ../services/chat-service
    container_name: chat-service-dev
    environment:
      # 外部API配置
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:password@mongodb:27017/baidaohui?authSource=admin}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - R2_BUCKET=${R2_BUCKET}
      - R2_ENDPOINT=${R2_ENDPOINT}
      # 内部配置
      - NODE_ENV=development
      - PORT=5003
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-change-in-production
    ports:
      - "5003:5003"
    depends_on:
      - redis
      - mongodb
    networks:
      - baidaohui-network

  # 算命服务
  fortune-service:
    build: ../services/fortune-service
    container_name: fortune-service-dev
    environment:
      # 外部API配置
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:password@mongodb:27017/baidaohui?authSource=admin}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - R2_BUCKET=${R2_BUCKET}
      - R2_ENDPOINT=${R2_ENDPOINT}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
      # 内部配置
      - NODE_ENV=development
      - PORT=5007
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - FORTUNE_SERVICE_KEY=dev-fortune-key
      - EMAIL_SERVICE_URL=http://email-service:5008
      - PAYMENT_SERVICE_URL=http://payment-service:5005
    ports:
      - "5007:5007"
    depends_on:
      - mongodb
    networks:
      - baidaohui-network

  # 邮件服务
  email-service:
    build: ../services/email-service
    container_name: email-service-dev
    environment:
      # 外部API配置
      - MJ_APIKEY_PUBLIC=${MJ_APIKEY_PUBLIC}
      - MJ_APIKEY_PRIVATE=${MJ_APIKEY_PRIVATE}
      # 内部配置
      - NODE_ENV=development
      - PORT=5008
      - FROM_EMAIL=noreply@localhost
      - REPLY_TO_EMAIL=support@localhost
      - AUTH_SERVICE_URL=http://auth-service:5001
    ports:
      - "5008:5008"
    networks:
      - baidaohui-network

  # 支付服务
  payment-service:
    build: ../services/payment-service
    container_name: payment-service-dev
    environment:
      # 外部API配置
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:password@mongodb:27017/baidaohui?authSource=admin}
      # 内部配置
      - NODE_ENV=development
      - PORT=5005
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - FRONTEND_URL=http://localhost:5173
      - FORTUNE_SERVICE_URL=http://fortune-service:5007
    ports:
      - "5005:5005"
    depends_on:
      - mongodb
    networks:
      - baidaohui-network

  # 其他服务可根据需要添加... 