version: '3.8'

services:
  exchange-rate-updater:
    build:
      context: .
      dockerfile: Dockerfile.exchange-updater
    container_name: exchange-rate-updater
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_URL}
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      - FORTUNE_SERVICE_URL=${FORTUNE_SERVICE_URL}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    volumes:
      - ./logs:/var/log
    networks:
      - baidaohui-network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  baidaohui-network:
    external: true 