name = "baidaohui-pages"
compatibility_date = "2024-01-01"

[env.production]
name = "baidaohui-pages"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "baidaohui-storage"

# 开发环境
[env.development]
name = "baidaohui-pages-dev"
compatibility_date = "2023-12-01"

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "baidaohui-storage-dev"

[env.development.vars]
ENVIRONMENT = "development"
DOMAIN = "localhost:3000"

# Pages 配置
[build]
command = "npm run build"
cwd = "."
watch_dir = "cloudflare/pages-functions"

[build.upload]
format = "modules"
dir = "cloudflare/pages-functions"
main = "./index.js" 