name = "baidaohui-pages"
compatibility_date = "2023-12-01"

[env.production]
name = "baidaohui-pages"
compatibility_date = "2023-12-01"

# R2 绑定
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "baidaohui-storage"

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"
DOMAIN = "baidaohui.com"

# 开发环境
[env.development]
name = "baidaohui-pages-dev"
compatibility_date = "2023-12-01"

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "baidaohui-storage-dev"

[env.development.vars]
ENVIRONMENT = "development"
DOMAIN = "localhost:3000"

# Pages 配置
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules" 